name: GitHub CI

on: [push, pull_request]

jobs:
  Windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Cygwin
        uses: egor-tensin/setup-cygwin@v1
        with:
          packages: rsync patch diffutils make unzip m4 findutils time wget curl git mingw64-x86_64-binutils mingw64-x86_64-gcc-core mingw64-x86_64-gcc-g++ mingw64-x86_64-pkg-config mingw64-x86_64-windows_default_manifest mingw64-x86_64-headers mingw64-x86_64-runtime mingw64-x86_64-pthreads mingw64-x86_64-zlib mingw64-x86_64-gmp python3

      - name: Create home dir
        run: |
          C:\tools\cygwin\bin\bash.exe --login -c 'env'

      - name: Run common platform script
        run: |
          C:\tools\cygwin\bin\bash.exe coq_platform_make.sh
